### PR TITLE
Create rubiks-cube-base.html

### PR DESCRIPTION
**Pull request by paulmasson**
I wanted a basic set of moving interactive cubes with minimal code. It took several days to get it to work nicely, but it was worth it for understanding what happens when objects are reassigned to different parents. Interested?

### CODE REVIEW

**Comment by theo-armour** [comment]
Cool. I will invite you to join jaanga - so you push yourself

**Comment by theo-armour** [comment]
nice tight code. cool!

**Comment by theo-armour** [comment]
What I was playing with this week:

http://theo-armour.github.io/theo-armour.testing/opendesk-half-sheet-table/opendesk-half-sheet-table-r2.html

A work in progress

---

BTW, I'm off tomorrow to attend Eloise's graduation in San Luis Obispo...

**Comment by theo-armour** [comment]
Don't you wish one could change one's parents as easily...

**Comment by paulmasson** [comment]
Amen to that.

**Comment by paulmasson** [comment]
Merged an update to Rubik’s cube to remove an unnecessary variable.

Any guidelines on how you like to work? Or can you just reverse merges of which you don’t approve? Don’t want to mess up anything particularly dear.

**Comment by theo-armour** [comment]
Hi Paul

Thanks for all the fixes. Sorry for the slow replies.

> > Any guidelines on how you like to work?

Fixes should be in the style of the original/main author of the script
being fixed.

My general thrust is to follow in Mr.doob's footsteps, as shown here:
- http://mrdoob.github.io/three.js/examples/
- https://github.com/mrdoob/three.js/wiki/Mr.doob's-Code-Style%E2%84%A2
- and, especially, here: 'The aim of the project is to create a
  lightweight 3D library with a very low level of complexity — in other
  words, for dummies.'

In other words, a visitor to Jaanga that is familiar with Mr.doobs style -
like it or not - should feel completely at ease with the code in Jaanga.

The code is _not_ written for full stack developers. On the contrary it is
written for engineers, designers and scientists - people who may have huge
domain expertise but just a limited amount of coding talent.

> > Or can you just reverse merges of which you don’t approve? Don’t want to
> > mess up anything particularly dear.

Minor edits and corrections: just do it.

If more about adding a new function or editing the way an algorithm works
the I like seeing a new release. This is really old-school, I know. I just
like to be able to compare two versions code and display / side by side and
numbered releases make that easy. Yes, full stack developers can do this
sort of thing with Git quite easily but I feel the Jaanga audience is not
at that level - which includes me.

Theo

**Pull request merged**
